name: Build and publish
on:
  push:
    tags:
      - "*"
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to build'
        required: true
        default: '0.1.0'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Get NWJS node-version
        run: echo This event
        if: ${{ github.event_name == 'workflow_dispatch'}}
        run: echo "NW=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - run: mkdir build && mkdir setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Чек версии
        run: |
          bash .github/workflows/is_latest.sh
      - name: Build
        run: |
          npm i
          npm run build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: setup/YourRadioLiteSetup.exe
          tag: ${{ env.NW }}
          overwrite: true
          file_glob: true