name: Build and publish
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Get NWJS version
        run: |
          echo "NW=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "repository variable : ${{ env.NW }}"
      - uses: actions/checkout@v4
      