name: TEST

on:
  release:
    types: [ created ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to build'
        required: true
        default: '0.88.0'
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  is-latest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check if latest
        working-directory: .github/workflows
        run: bash ./is_latest.sh ${{ github.event_name }}
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
  build-release:
    needs: [ is-latest ]
    name: "Build Release"
    runs-on: "windows-latest"
    steps:
      - name: Get NWJS version
        run: |
          if ( "${{ github.event_name }}" = "workflow_dispatch" ) then
            echo "NW=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "NW=$(curl -s https://nwjs.io/versions | jq -r '.latest' | sed 's/v//')" >> $GITHUB_ENV
          fi
          echo $GITHUB_ENV
